install.sh

Works with https://github.com/teaxyz/cli/pull/36

Add fish hook

---

install.sh

PR into #6, so I can clean up the fish stuff as well. These changes are mostly suggested by `shellcheck`, but some (like using `test` throughout) are just for consistency.

Pass all shellcheck tests

---

.github/workflows/ci.yml
install.sh

We're currently passing. Might as well keep ourselves honest.

Add `shellcheck` to CI

---

.github/workflows/ci.yml

ie. no SRCROOT, no README no git

test we work in an empty scenario

---

.github/workflows/ci.yml
action.js
install.sh

teaxyz/setup works over existing tea.xyz install

---

install.sh

the main pantry is still private so people can’t really do much

k, time for TEA_SECRET to go away

---

install.sh

`sw_vers` seems to be their `uname`.
resolves #44

exclude macos < 11

---

install.sh

don't say we installed if we're just `exec`ing

---

install.sh

Depends on https://github.com/teaxyz/cli/pull/149 else it errors on `typedef`.

adds fish shell magic

---

.github/workflows/ci.yml
install.sh

Fixes https://github.com/teaxyz/cli/issues/178

Fix infinite loop

---

install.sh

fixes https://github.com/teaxyz/setup/pull/85#issuecomment-1328059796

gum > gum_func

---

.github/workflows/ci.yml
action.js
action.yml
install.sh

allow install.sh to use specific versions

---

.github/workflows/ci.yml
install.sh

More complete test for /usr/local/bin creatability. Includes CI test.

better /usr/local/bin checks with test

---

.github/workflows/ci.yml
install.sh

fix running in an env without `which`

---

.github/workflows/ci.yml
install.sh

Fixes https://github.com/teaxyz/setup/issues/107

properly test no sudo/run as root

---

install.sh

Adds support the [Elvish shell](https://elv.sh/).
Depends on https://github.com/teaxyz/cli/pull/340

Add support for Elvish Shell

---

install.sh

This fixes the problem where $SHELL isn't available _even in .bashrc_; at least in docker images based on debian:buster-slim.
resolves https://github.com/teaxyz/setup/issues/131

more explicit magic and even more shell detection

---

.github/workflows/cd.yml
.github/workflows/ci-pre-reqs.yml
.github/workflows/vx-tagger.yml

resolves https://github.com/teaxyz/setup/issues/135

reduce GHA permissions

---

installer.sh

this should fix the vast majority of builds that are failing tests on arch. EIMGTOOMINIMAL

archlinux needs libs/headers

---

installer.sh

proof of concept [here](https://github.com/pkgxdev/pantry/pull/4443)
closes https://github.com/pkgxdev/pantry/pull/4443

add `gcc` on archlinux
